# Generated by Django 5.0.4 on 2024-05-11 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '6. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '7. Students'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '8. Enrolled Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.CharField(default='Unspecified', max_length=200),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('featured_img', models.ImageField(null=True, upload_to='course_imgs/')),
                ('techs', models.TextField(null=True)),
                ('duration', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_internships', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '5. Internships',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('featured_img', models.ImageField(null=True, upload_to='course_imgs/')),
                ('techs', models.TextField(null=True)),
                ('duration', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_trainings', to='main.teacher')),
            ],
            options={
                'verbose_name_plural': '4. Trainings',
            },
        ),
    ]
