# Generated by Django 5.0.4 on 2024-05-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_chapter_coursechapter_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipchapter',
            options={'verbose_name_plural': '8. Intership Chapters'},
        ),
        migrations.AlterModelOptions(
            name='trainingchapter',
            options={'verbose_name_plural': '7. Training Chapters'},
        ),
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course_student', to='main.student'),
        ),
        migrations.CreateModel(
            name='StudentInternshipEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_internship', to='main.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_internship_student', to='main.student')),
            ],
            options={
                'verbose_name_plural': '12. Enrolled Internship',
            },
        ),
        migrations.CreateModel(
            name='StudentTrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_training_student', to='main.student')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_training', to='main.training')),
            ],
            options={
                'verbose_name_plural': '11. Enrolled Training',
            },
        ),
    ]
