# Generated by Django 5.0.4 on 2024-05-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_internshipchapter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechapter',
            options={'verbose_name_plural': '6. Course Chapters'},
        ),
    ]
