# Generated by Django 5.0.4 on 2024-05-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_roadmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'verbose_name_plural': '13. Roadmaps'},
        ),
    ]
